//! Validation binding primitives.
mod argument_reader;
mod bind_error;
mod bind_error_kind;
mod bound_validation_context;
mod bound_validator;
mod dependency_spec;
mod execution_error;
mod execution_error_kind;
mod input_type;
mod prepared_validator;
mod prepared_outcome;
mod rule_outcome;
mod validation_value;
mod text_validator_adapter;
mod typed_validator_adapter;
mod validation_outcome;
mod violation_draft;
pub use argument_reader::ArgumentReader;
pub use bind_error::BindError;
pub use bind_error_kind::BindErrorKind;
pub use bound_validation_context::BoundValidationContext;
pub use bound_validator::BoundValidator;
pub use dependency_spec::DependencySpec;
pub use execution_error::ExecutionError;
pub use execution_error_kind::ExecutionErrorKind;
pub use input_type::InputType;
pub use prepared_validator::{PrepareFn, PreparedValidator};
pub use prepared_outcome::PreparedOutcome;
pub use rule_outcome::RuleOutcome;
pub use validation_value::ValidationValue;
pub use validation_outcome::ValidationOutcome;
pub use violation_draft::ViolationDraft;
pub use text_validator_adapter::prepare_text_validator;
pub use typed_validator_adapter::prepare_typed_validator;
pub(crate) use crate::registry::ValidatorSignature;
pub(crate) use crate::report::{SkipReason, ValidationPath};
