// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================

//! Validator registrations for the next-generation registry.

use super::ValidatorDescriptor;
use crate::RegistrationSource;
use crate::ValidatorId;

/// One validator definition associated with a stable identifier.
#[derive(Clone, Copy, Debug)]
pub struct ValidatorRegistration {
    /// Stable identifier claimed by the registration.
    id: ValidatorId,
    /// Immutable descriptor for every supported input shape.
    descriptor: &'static ValidatorDescriptor,
    /// Compile-time source metadata used in duplicate diagnostics.
    source: RegistrationSource,
}

impl ValidatorRegistration {
    /// Creates a validator registration from its identifier, descriptor, and
    /// source.
    ///
    /// `id` is the stable validator identifier, `descriptor` defines the
    /// supported signatures, and `source` records where the registration was
    /// declared. The descriptor must live for the duration of the program.
    /// This constructor only stores the supplied values and does not access
    /// the file system. It can be used for local registrations as well as the
    /// registrations generated by `register_validator!`.
    #[must_use]
    #[inline]
    pub const fn new(id: ValidatorId, descriptor: &'static ValidatorDescriptor, source: RegistrationSource) -> Self {
        Self { id, descriptor, source }
    }

    /// Returns the stable identifier.
    #[must_use]
    #[inline]
    pub const fn id(&self) -> ValidatorId {
        self.id
    }

    /// Returns the immutable descriptor.
    #[must_use]
    #[inline]
    pub const fn descriptor(&self) -> &'static ValidatorDescriptor {
        self.descriptor
    }

    /// Returns the source location used for duplicate diagnostics.
    #[must_use]
    #[inline]
    pub const fn source(&self) -> RegistrationSource {
        self.source
    }
}
